"use client";

import { MyProvider } from "@/store/myContext";
import localFont from "next/font/local";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Welcome Hablu mama",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* For Context Api */}

        <Toaster />

        {pathname !== "/userLists" ? (
          <ul className="navbar">
            <li>
              <Link href="/" className={`${pathname === "/" ? "active" : ""}`}>
                Home
              </Link>
            </li>
            <li>
              <Link
                href="/about"
                className={`${pathname === "/about" ? "active" : ""}`}
              >
                About
              </Link>
            </li>
            <li>
              <Link
                href="/meals"
                className={`${pathname === "/meals" ? "active" : ""}`}
              >
                Meals
              </Link>
            </li>
            <li>
              <Link
                href="/userLists"
                className={`${pathname === "/userList" ? "active" : ""}`}
              >
                User Lists
              </Link>
            </li>
          </ul>
        ) : (
          <Link href="/">Go Home</Link>
        )}
        <MyProvider>{children}</MyProvider>
      </body>
    </html>
  );
}
